### ISSUE TITLE
Data sets that we are currently looking at

### ISSUE THREAD

**Issue by rhiever** [rhiever/sklearn-benchmarks#1]
Here are the data sets that we are currently looking at. If you would like to contribute a data set, please see our data set requirements in the [contributing guidelines](https://github.com/rhiever/sklearn-benchmarks/blob/master/CONTRIBUTING.md).
1.  http://yann.lecun.com/exdb/mnist/ 
2.  https://www.cs.toronto.edu/~kriz/cifar.html
3.  http://qwone.com/~jason/20Newsgroups/
4.  http://www.cs.toronto.edu/~delve/data/twonorm/desc.html
5.  http://www.cs.toronto.edu/~delve/data/ringnorm/desc.html
6.  http://www.cs.toronto.edu/~delve/data/mushrooms/desc.html
7.  http://www.cs.toronto.edu/~delve/data/letter/desc.html
8.  http://www.cs.toronto.edu/~delve/data/image-seg/desc.html
9.  http://www.cs.toronto.edu/~delve/data/titanic/desc.html
10. http://www.cs.toronto.edu/~delve/data/splice/desc.html
11. http://www.cs.toronto.edu/~delve/data/adult/desc.html
12. http://archive.ics.uci.edu/ml/datasets/Iris
13. http://archive.ics.uci.edu/ml/datasets/Wine
14. http://archive.ics.uci.edu/ml/datasets/Car+Evaluation
15. http://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+%28Diagnostic%29
16. http://archive.ics.uci.edu/ml/datasets/Abalone
17. http://archive.ics.uci.edu/ml/datasets/Wine+Quality
18. http://archive.ics.uci.edu/ml/datasets/Heart+Disease
19. http://archive.ics.uci.edu/ml/datasets/Poker+Hand
20. http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones
21. http://archive.ics.uci.edu/ml/datasets/Internet+Advertisements
22. http://archive.ics.uci.edu/ml/datasets/MAGIC+Gamma+Telescope
23. http://archive.ics.uci.edu/ml/datasets/Chess+%28King-Rook+vs.+King-Knight%29
24. http://archive.ics.uci.edu/ml/datasets/Statlog+%28Vehicle+Silhouettes%29
25. http://archive.ics.uci.edu/ml/datasets/Dorothea
26. http://archive.ics.uci.edu/ml/datasets/Audiology+%28Standardized%29
27. http://archive.ics.uci.edu/ml/datasets/Echocardiogram
28. http://archive.ics.uci.edu/ml/datasets/Spambase
29. http://archive.ics.uci.edu/ml/datasets/Covertype
30. http://archive.ics.uci.edu/ml/datasets/Glass+Identification
31. http://archive.ics.uci.edu/ml/datasets/Yeast
32. http://archive.ics.uci.edu/ml/datasets/Ionosphere
33. http://archive.ics.uci.edu/ml/datasets/Gisette
34. http://archive.ics.uci.edu/ml/datasets/Madelon
35. http://archive.ics.uci.edu/ml/datasets/University
36. http://archive.ics.uci.edu/ml/datasets/Statlog+%28Landsat+Satellite%29
37. http://archive.ics.uci.edu/ml/datasets/Ozone+Level+Detection
38. http://archive.ics.uci.edu/ml/datasets/Hill-Valley
39. http://archive.ics.uci.edu/ml/datasets/Flags
40. http://archive.ics.uci.edu/ml/datasets/Ecoli
41. http://archive.ics.uci.edu/ml/datasets/Hepatitis
42. https://www.kaggle.com/c/whats-cooking/data
43. https://www.kaggle.com/c/sf-crime/data
44. https://www.kaggle.com/c/facial-keypoints-detection/data
45.   http://rodrigob.github.io/are_we_there_yet/build/classification_datasets_results.html
46.   Data sets in https://github.com/vincentarelbundock/Rdatasets (?)
47.   https://www.kaggle.com/datasets

**Comment by rasbt** [comment]
Here are some more:

- The Large Movie Review Dataset http://ai.stanford.edu/~amaas/data/sentiment/. It's pretty nice and clean, and definitely a good way for benchmarking classifiers (it's binary and the classes are uniform, which is nice)
- Then, there's MNIST of course: http://yann.lecun.com/exdb/mnist/

**Comment by davidgasquez** [comment]
What do you think about moving those *requirements* to a `contributing.md` file to make a standard format?

**Comment by rhiever** [comment]
Will do.

On Sunday, February 7, 2016, David Gasquez <notifications@github.com> wrote:

> What do you think about moving those *requirements* to a contributing.md
> file to make a standard format?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/sklearn-benchmarks/issues/1#issuecomment-181120748>
> .
>


-- 
Randal S. Olson, Ph.D.
Postdoctoral Researcher, Institute for Biomedical Informatics
University of Pennsylvania

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com

**Comment by ledell** [comment]
Are you limiting the datasets to those that can be easily uploaded to a GitHub repo?  I am curious about the focus on toy/small sized datasets.  Have you considered using LFS or S3 as a place to store larger datasets?

**Comment by rhiever** [comment]
That definitely sounds feasible in the long-term. Right now, we're focusing on GitHub as a place to develop the pipeline with smaller data sets (with some exceptions, e.g., MNIST and CIFAR), with the idea that we can port it to a scalable system later if we want to focus on *much* larger data sets. The nice part is that this sort of parameter sweep is trivially parallelizable across many cores.

OpenML.org also seems like a viable place to port this work in the long run. I believe their Python interface will be released in March.
