### ISSUE TITLE
searching max_iter in LinearSVC?

### ISSUE THREAD

**Issue by amueller** [rhiever/sklearn-benchmarks#14]
I'm a bit surprised that you search over ``max_iter`` in ``LinearSVC`` https://github.com/rhiever/sklearn-benchmarks/blob/master/model_code/LinearSVC.py#L12 What is the purpose of that? Checking if few iterations are enough? And where did you get these values from? I'd be surprised if this ever stopped early.
Also, I see you are trying out hinge and squared hinge, but you are not searching over L1 vs L2 penalty.

**Comment by rhiever** [comment]
A lot of these parameters came from that DefaultGridSearch issue that we were discussing months ago. They had chosen a bunch of parameters and ranges there, and everyone seemed happy with them, so I figured that was a good starting point. :-)

If you have suggestions for specific parameters/parameter ranges for each model, I can queue those up for the benchmark pretty easily.
