### ISSUE TITLE
Code duplication?

### ISSUE THREAD

**Issue by amueller** [rhiever/sklearn-benchmarks#15]
Maybe a silly question but why do you have a separate ``.py`` file for each classifier? The code is the same for all, right?

Also, have you checked out skll?

**Comment by rhiever** [comment]
It was easier to run them on the HPCC that way. :-)

```python
for dataset in [`datasets`]:
    for model in [`models.py` ...]:
        # benchmark model on dataset
```

**Comment by amueller** [comment]
ok but you could still just have all the stuff in a single function and call that in each file ;)
