### ISSUE TITLE
Unconditional search in SVC

### ISSUE THREAD

**Issue by amueller** [rhiever/sklearn-benchmarks#20]
The way you search in SVC using the cross-product of the kernel parameter doesn't really make sense.
Did you do that for simplicity? [you try about 150 different kernel parameter settings with the linear kernel, which just ignores them]
Also, I wouldn't search over shrinking.

**Comment by rhiever** [comment]
Yes, it's pretty much for simplicity. Should've put a conditional in that loop, I suppose.

>Also, I wouldn't search over shrinking.

How come?

**Comment by amueller** [comment]
It's a speed optimization. Again, it depends a bit on what your goal is. But the results should be identical. And you don't record the training time, so it doesn't actually help to get better (faster) default parameters.

**Comment by rhiever** [comment]
Gotcha. Didn't know that about shrinking. :-)
