### ISSUE TITLE
Searching over ``n_neighbors`` in KNeighborsClassifier weird

### ISSUE THREAD

**Issue by amueller** [rhiever/sklearn-benchmarks#22]
https://github.com/rhiever/sklearn-benchmarks/blob/master/model_code/KNeighborsClassifier.py#L12

As you use many small datasets, it can happen that there are not even 100 points, so the classifier will fail, right?

Also, the optimum ``n_neighbors`` is always 3, which is not one of the parameters you tried ;D

**Comment by rhiever** [comment]
>As you use many small datasets, it can happen that there are not even 100 points, so the classifier will fail, right?

Yep! That's why we wrap the training part in a try/exception, so it will fail silently and move on.

>Also, the optimum `n_neighbors` is always 3, which is not one of the parameters you tried ;D

Why is that? IIRC we found that the ideal `n_neighbors` is 10, although that was just from a quick analysis.

**Comment by amueller** [comment]
ah, ok. that makes sense for the exception. That means smaller models try out less parameter settings. I'm not sure if it makes sense to scale ``k`` proportionally to the number of samples or not. IIRC 3 is optimum on MNIST, and that's the only one that counts, right?

**Comment by rhiever** [comment]
>IIRC 3 is optimum on MNIST, and that's the only one that counts, right?

Haha! I thought CIFAR was the one that matters nowadays. ;-)
