### ISSUE TITLE
Experiments in model_code not centralized

### ISSUE THREAD

**Issue by PG-TUe** [rhiever/sklearn-benchmarks#33]
Currently a lot of code is shared between various scripts in the model_code folder. Shared logic includes preprocessing the dataset, evaluating the classifier on a set of metrics and outputting results. Of course, because the code is not centralized, whenever something needs to be added or changed, it needs to be done in many files. This results in mistakes or inconsistencies such as the `parameter_string` having a trailing comma in [logistic regression](https://github.com/rhiever/sklearn-benchmarks/blob/master/model_code/LogisticRegression.py#L50) but not in [Bernoulli NB](https://github.com/rhiever/sklearn-benchmarks/blob/master/model_code/BernoulliNB.py#L42).

I have created a [fork on my github](https://github.com/PG-TUe/sklearn-benchmarks/tree/unify-modelcode), which has one generalized function for executing the benchmark and formatting the output, called [`evaluate_model`](https://github.com/PG-TUe/sklearn-benchmarks/blob/unify-modelcode/model_code/evaluate_model.py). Configurations for each algorithm can be passed to the function, examples of this can be seen in [NewBernoulliNB.py](https://github.com/PG-TUe/sklearn-benchmarks/blob/unify-modelcode/model_code/NewBernoulliNB.py) and [NewLogisticRegression.py](https://github.com/PG-TUe/sklearn-benchmarks/blob/unify-modelcode/model_code/NewLogisticRegression.py).

From testing locally on a small dataset, both the old and new way reproduce identical results*. Please let me know if this is of interest to you. If so, I could possibly rework the other algorithms, review my code, and do a pull request.

\* Though LR no longer has a trailing comma in the `parameter_string`, and `random_state` is included in the `parameter_string` for LR.

**Comment by rhiever** [comment]
I'm 👍 on merging this functionality into this repo.

**Comment by rhiever** [comment]
Merged. Thanks @PG-TUe!

**Comment by PG-TUe** [comment]
Already forgot about this! ^^' No problem :D

**Comment by rhiever** [comment]
Figured we might as well do some cleaning up on the repo since the paper is coming out. :-)
